services:
  postgres:
    container_name: clinical-database
    build:
      context: ./scripts
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/18/data


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080


volumes:
  db: